const buildInstructions = ({ prep, season, cook, base, assemble, quick, fatLoss, muscleGain }) => [
  {
    step: 1,
    title: 'Preparer les ingredients',
    description: prep,
  },
  {
    step: 2,
    title: 'Assaisonner simplement',
    description: season || 'Ajoute du sel, du poivre, du cumin et du paprika. Si tu as du citron, mets quelques gouttes pour donner plus de gout sans ajouter beaucoup de calories.',
  },
  {
    step: 3,
    title: 'Cuire la partie principale',
    description: cook,
  },
  {
    step: 4,
    title: 'Preparer la base',
    description: base,
  },
  {
    step: 5,
    title: 'Assembler le repas',
    description: assemble,
  },
  {
    step: 6,
    title: 'Adapter a ton objectif',
    description: `Version rapide: ${quick} Version fat loss: ${fatLoss} Version muscle gain: ${muscleGain}`,
  },
];

const RECIPE_SEEDS = [
  {
    title: 'Omelette tomate fromage',
    category: 'breakfast',
    description: 'Omelette rapide, rassasiante et riche en proteines avec une touche marocaine.',
    prepTimeMinutes: 10,
    calories: 390,
    proteinG: 28,
    carbsG: 12,
    fatG: 25,
    difficulty: 'facile',
    tags: ['proteine', 'rapide', 'petit-dejeuner'],
    ingredients: [
      { name: 'oeufs', quantity: 3, unit: 'pieces' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'fromage', quantity: 30, unit: 'g' },
      { name: 'huile d olive', quantity: 5, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 3 oeufs, 1 tomate, 30g de fromage, 1 cuillere a cafe d huile d olive, du sel, du poivre et du cumin. Lave la tomate puis coupe-la en petits des pour qu elle cuise vite.',
      season: 'Casse les oeufs dans un bol. Ajoute sel, poivre, cumin et paprika si tu en as. Bats 20 a 30 secondes avec une fourchette pour obtenir un melange uniforme.',
      cook: 'Fais chauffer une poele antiadhesive a feu moyen. Ajoute l huile, verse la tomate et laisse cuire 2 minutes. Ajoute les oeufs puis cuis 4 a 6 minutes a feu doux-moyen.',
      base: 'Coupe le fromage en petits morceaux ou rape-le. Ajoute-le quand les oeufs commencent a prendre pour qu il fonde sans bruler.',
      assemble: 'Plie l omelette ou laisse-la ouverte dans l assiette. Ajoute un peu de tomate fraiche ou de persil si disponible.',
      quick: 'cuits tout ensemble dans une petite poele et mange directement.',
      fatLoss: 'utilise 2 oeufs entiers + 1 blanc et limite le fromage a 15g.',
      muscleGain: 'garde les 3 oeufs, ajoute du pain complet ou un yaourt a cote.',
    }),
  },
  {
    title: 'Sandwich thon tomate',
    category: 'budget_student',
    description: 'Sandwich economique et tres proteine, parfait entre deux seances.',
    prepTimeMinutes: 5,
    calories: 430,
    proteinG: 34,
    carbsG: 48,
    fatG: 10,
    difficulty: 'facile',
    tags: ['budget', 'rapide', 'thon'],
    ingredients: [
      { name: 'thon', quantity: 120, unit: 'g' },
      { name: 'pain', quantity: 100, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'citron', quantity: 0.5, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 120g de thon, 100g de pain, 1 tomate, un demi citron, sel, poivre et cumin. Egoutte bien le thon pour eviter un sandwich trop humide.',
      season: 'Mets le thon dans un bol. Ajoute citron, poivre, cumin et un peu de sel. Ecrase legerement avec une fourchette pour repartir les epices.',
      cook: 'Aucune cuisson obligatoire. Si tu veux un sandwich chaud, chauffe le pain 1 a 2 minutes a feu doux dans une poele seche.',
      base: 'Coupe la tomate en fines tranches. Ouvre le pain sans le casser et retire un peu de mie si tu veux alleger les calories.',
      assemble: 'Mets le thon dans le pain, ajoute les tomates puis referme. Presse doucement pour que tout tienne bien.',
      quick: 'melange thon et tomate directement dans le pain en moins de 5 minutes.',
      fatLoss: 'utilise moins de pain et ajoute concombre ou salade pour plus de volume.',
      muscleGain: 'ajoute un oeuf dur ou un deuxieme pain si tu as besoin de plus d energie.',
    }),
  },
  {
    title: 'Bowl riz poulet',
    category: 'lunch',
    description: 'Bowl complet pour construire du muscle sans exploser les lipides.',
    prepTimeMinutes: 20,
    calories: 620,
    proteinG: 48,
    carbsG: 76,
    fatG: 12,
    difficulty: 'moyen',
    tags: ['muscle_gain', 'meal-prep', 'post-training'],
    ingredients: [
      { name: 'poulet', quantity: 160, unit: 'g' },
      { name: 'riz', quantity: 220, unit: 'g cuit' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'huile d olive', quantity: 5, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 160g de poulet, 220g de riz cuit, 1 tomate, 1 cuillere a cafe d huile d olive, sel, poivre, paprika et cumin. Coupe le poulet en petits morceaux pour qu il cuise plus vite.',
      season: 'Mets le poulet dans un bol. Ajoute sel, poivre, paprika, cumin et un filet de citron si disponible. Melange bien pour couvrir tous les morceaux.',
      cook: 'Fais chauffer une poele antiadhesive a feu moyen. Ajoute tres peu d huile, mets le poulet et cuis 6 a 8 minutes en remuant jusqu a ce qu il soit dore et completement cuit.',
      base: 'Rechauffe le riz 1 a 2 minutes a la poele ou au micro-ondes avec une cuillere d eau. Si le riz est cru, cuis-le dans l eau salee selon le paquet.',
      assemble: 'Mets le riz dans un bol, ajoute le poulet par-dessus, puis la tomate coupee en des. Termine avec l huile d olive ou une sauce yaourt legere.',
      quick: 'utilise du riz deja cuit et du poulet cuit de meal prep.',
      fatLoss: 'garde peu d huile et ajoute plus de tomate, concombre ou salade.',
      muscleGain: 'augmente le riz ou ajoute un yaourt proteine a cote.',
    }),
  },
  {
    title: 'Salade thon oeufs',
    category: 'dinner',
    description: 'Assiette fraiche, dense en proteines et facile a digerer le soir.',
    prepTimeMinutes: 10,
    calories: 410,
    proteinG: 39,
    carbsG: 16,
    fatG: 21,
    difficulty: 'facile',
    tags: ['fat_loss', 'low-carb', 'proteine'],
    ingredients: [
      { name: 'thon', quantity: 100, unit: 'g' },
      { name: 'oeufs', quantity: 2, unit: 'pieces' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'oignon', quantity: 0.5, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 100g de thon, 2 oeufs, 1 tomate, un demi oignon, citron, sel, poivre et cumin. Lave la tomate et coupe l oignon tres fin pour qu il soit plus doux.',
      season: 'Dans un bol, melange le thon avec citron, poivre et cumin. Goute avant d ajouter du sel car le thon en boite est souvent deja sale.',
      cook: 'Mets les oeufs dans une casserole d eau froide. Porte a ebullition puis cuis 9 a 10 minutes a feu moyen pour obtenir des oeufs durs.',
      base: 'Refroidis les oeufs sous l eau froide, ecale-les puis coupe-les en quartiers. Coupe la tomate en des.',
      assemble: 'Dans une assiette, mets tomate et oignon, ajoute le thon puis les oeufs. Melange legerement pour ne pas casser les oeufs.',
      quick: 'utilise des oeufs deja cuits et assemble en 3 minutes.',
      fatLoss: 'mets 1 oeuf entier + 1 blanc et ajoute plus de legumes.',
      muscleGain: 'ajoute du pain complet, du riz ou des pois chiches.',
    }),
  },
  {
    title: 'Avoine banane whey',
    category: 'breakfast',
    description: 'Bol energie pour matin actif ou prise de masse propre.',
    prepTimeMinutes: 5,
    calories: 520,
    proteinG: 38,
    carbsG: 74,
    fatG: 9,
    difficulty: 'facile',
    tags: ['whey', 'bulking', 'rapide'],
    ingredients: [
      { name: 'avoine', quantity: 70, unit: 'g' },
      { name: 'banane', quantity: 1, unit: 'piece' },
      { name: 'whey', quantity: 30, unit: 'g' },
      { name: 'lait', quantity: 200, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 70g d avoine, 1 banane, 30g de whey et 200ml de lait. Prends un bol assez grand pour melanger sans renverser.',
      season: 'Ajoute une pincee de cannelle si tu en as. Evite de trop sucrer: la banane apporte deja beaucoup de gout.',
      cook: 'Pour une version chaude, chauffe avoine et lait 2 a 3 minutes a feu doux ou au micro-ondes. Remue a mi-cuisson pour eviter que ca colle.',
      base: 'Laisse tiedir 1 minute avant d ajouter la whey, sinon elle peut faire des grumeaux. Melange energiquement avec une cuillere.',
      assemble: 'Coupe la banane en rondelles et pose-la au-dessus. Ajoute un peu d eau ou de lait si la texture est trop epaisse.',
      quick: 'melange tout froid dans un shaker-bol et mange directement.',
      fatLoss: 'baisse l avoine a 40g et garde la whey pour les proteines.',
      muscleGain: 'ajoute plus d avoine, du lait entier ou une cuillere de beurre de cacahuete.',
    }),
  },
  {
    title: 'Yaourt grec banane',
    category: 'snack',
    description: 'Snack frais, simple et efficace pour remonter les proteines.',
    prepTimeMinutes: 5,
    calories: 260,
    proteinG: 24,
    carbsG: 35,
    fatG: 2,
    difficulty: 'facile',
    tags: ['snack', 'rapide', 'fat_loss'],
    ingredients: [
      { name: 'yaourt', quantity: 250, unit: 'g' },
      { name: 'banane', quantity: 1, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 250g de yaourt grec ou skyr et 1 banane. Prends un bol froid si possible pour garder une texture agreable.',
      season: 'Ajoute cannelle, vanille ou quelques gouttes de citron. Ne mets pas trop de miel si ton objectif est la perte de graisse.',
      cook: 'Aucune cuisson necessaire. Si le yaourt sort du frigo, laisse-le 2 minutes a temperature ambiante pour qu il soit moins compact.',
      base: 'Remue le yaourt 15 secondes pour le rendre plus cremeux. Coupe la banane en rondelles fines.',
      assemble: 'Mets le yaourt dans le bol, ajoute la banane, puis melange legerement ou garde les rondelles au-dessus.',
      quick: 'mange directement dans le pot avec une banane a cote.',
      fatLoss: 'utilise yaourt 0% et une demi-banane.',
      muscleGain: 'ajoute avoine ou whey pour augmenter calories et proteines.',
    }),
  },
  {
    title: 'Tajine poulet leger',
    category: 'dinner',
    description: 'Version sportive du tajine, riche en gout et controlee en calories.',
    prepTimeMinutes: 30,
    calories: 540,
    proteinG: 46,
    carbsG: 38,
    fatG: 20,
    difficulty: 'moyen',
    tags: ['maroc', 'diner', 'proteine'],
    ingredients: [
      { name: 'poulet', quantity: 180, unit: 'g' },
      { name: 'oignon', quantity: 1, unit: 'piece' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'huile d olive', quantity: 10, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 180g de poulet, 1 oignon, 1 tomate, 10ml d huile d olive, sel, poivre, curcuma, gingembre et cumin. Coupe l oignon finement et le poulet en morceaux moyens.',
      season: 'Mets le poulet dans un bol avec sel, poivre, curcuma, gingembre et cumin. Melange avec les mains ou une cuillere pour bien repartir les epices.',
      cook: 'Chauffe une marmite ou une poele profonde a feu moyen. Ajoute l huile puis l oignon 3 minutes. Ajoute le poulet et fais dorer 5 minutes.',
      base: 'Ajoute la tomate rapee ou coupee tres petit, puis un demi verre d eau. Baisse a feu doux et couvre 15 a 20 minutes.',
      assemble: 'Verifie que le poulet est cuit a coeur. Sers avec la sauce reduite, sans trop d huile, et ajoute persil ou citron si disponible.',
      quick: 'coupe le poulet petit et cuis en poele couverte pour gagner 10 minutes.',
      fatLoss: 'retire la peau du poulet et limite l huile a une cuillere a cafe.',
      muscleGain: 'ajoute riz, pommes de terre ou pain complet pour completer.',
    }),
  },
  {
    title: 'Lentilles proteinees',
    category: 'budget_student',
    description: 'Plat budget, rassasiant et parfait pour une journee chargee.',
    prepTimeMinutes: 25,
    calories: 480,
    proteinG: 29,
    carbsG: 72,
    fatG: 8,
    difficulty: 'facile',
    tags: ['budget-etudiant', 'fibres', 'vegetarien'],
    ingredients: [
      { name: 'lentilles', quantity: 250, unit: 'g cuites' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'oignon', quantity: 1, unit: 'piece' },
      { name: 'oeufs', quantity: 1, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 250g de lentilles cuites, 1 tomate, 1 oignon, 1 oeuf, sel, poivre, cumin et paprika. Coupe l oignon et la tomate en petits morceaux.',
      season: 'Dans une casserole, mets oignon, tomate, cumin, paprika, sel et poivre. Ajoute un peu d eau pour eviter que ca accroche.',
      cook: 'Fais cuire a feu moyen 5 minutes jusqu a ce que l oignon ramollisse. Ajoute les lentilles et laisse mijoter 8 a 10 minutes a feu doux.',
      base: 'Pendant ce temps, cuis l oeuf 9 a 10 minutes dans l eau bouillante, ou fais-le au plat 3 minutes a feu moyen.',
      assemble: 'Verse les lentilles dans une assiette creuse. Ajoute l oeuf coupe en deux et un peu de citron si tu en as.',
      quick: 'utilise des lentilles deja cuites en conserve et chauffe 5 minutes.',
      fatLoss: 'garde l oeuf mais evite d ajouter beaucoup d huile.',
      muscleGain: 'ajoute du pain complet ou du riz pour plus de glucides.',
    }),
  },
  {
    title: 'Pois chiches thon',
    category: 'lunch',
    description: 'Salade marocaine froide, riche en proteines et en glucides utiles.',
    prepTimeMinutes: 10,
    calories: 520,
    proteinG: 36,
    carbsG: 62,
    fatG: 14,
    difficulty: 'facile',
    tags: ['budget-etudiant', 'thon', 'meal-prep'],
    ingredients: [
      { name: 'pois chiches', quantity: 220, unit: 'g cuits' },
      { name: 'thon', quantity: 100, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'huile d olive', quantity: 5, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 220g de pois chiches cuits, 100g de thon, 1 tomate, 5ml d huile d olive, citron, cumin, sel et poivre. Rince les pois chiches si tu utilises une conserve.',
      season: 'Dans un bol, melange citron, cumin, poivre et huile d olive. Ajoute tres peu de sel car le thon peut deja etre sale.',
      cook: 'Aucune cuisson necessaire. Si tu preferes chaud, chauffe les pois chiches 3 a 4 minutes a feu doux avec une cuillere d eau.',
      base: 'Egoutte le thon et coupe la tomate en petits des. Retire un peu de jus de tomate si tu veux une salade moins humide.',
      assemble: 'Mets pois chiches, thon et tomate dans un grand bol. Verse l assaisonnement et melange doucement.',
      quick: 'assemble directement avec une conserve de pois chiches et une boite de thon.',
      fatLoss: 'diminue les pois chiches et ajoute concombre ou salade.',
      muscleGain: 'augmente les pois chiches ou ajoute du pain complet.',
    }),
  },
  {
    title: 'Steak pommes de terre',
    category: 'dinner',
    description: 'Repas classique post-training pour recharger sans complication.',
    prepTimeMinutes: 25,
    calories: 690,
    proteinG: 45,
    carbsG: 70,
    fatG: 24,
    difficulty: 'moyen',
    tags: ['post-training', 'muscle_gain', 'diner'],
    ingredients: [
      { name: 'steak', quantity: 160, unit: 'g' },
      { name: 'pommes de terre', quantity: 300, unit: 'g' },
      { name: 'huile d olive', quantity: 10, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 160g de steak, 300g de pommes de terre, 10ml d huile d olive, sel, poivre et paprika. Coupe les pommes de terre en cubes pour reduire le temps de cuisson.',
      season: 'Assaisonne le steak avec sel, poivre et paprika. Assaisonne aussi les pommes de terre avec une petite pincee de sel et du cumin si tu aimes.',
      cook: 'Cuis les pommes de terre dans l eau salee 12 a 15 minutes, jusqu a ce qu elles soient tendres. Egoutte-les puis fais-les dorer 3 minutes a feu moyen si tu veux.',
      base: 'Chauffe une poele a feu fort. Saisis le steak 2 a 4 minutes par face selon l epaisseur, puis laisse reposer 2 minutes hors du feu.',
      assemble: 'Mets les pommes de terre dans l assiette, ajoute le steak tranche et une tomate ou salade si disponible.',
      quick: 'utilise des pommes de terre deja cuites et rechauffe-les a la poele.',
      fatLoss: 'prends steak 5%, baisse l huile et ajoute plus de legumes.',
      muscleGain: 'augmente les pommes de terre ou ajoute du pain.',
    }),
  },
  {
    title: 'Wrap poulet',
    category: 'snack',
    description: 'Wrap rapide, transportable et tres pratique apres entrainement.',
    prepTimeMinutes: 10,
    calories: 510,
    proteinG: 42,
    carbsG: 52,
    fatG: 14,
    difficulty: 'facile',
    tags: ['post-training', 'rapide', 'poulet'],
    ingredients: [
      { name: 'poulet', quantity: 140, unit: 'g' },
      { name: 'pain', quantity: 90, unit: 'g' },
      { name: 'yaourt', quantity: 40, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 140g de poulet, 90g de pain type tortilla ou batbout fin, 40g de yaourt et 1 tomate. Coupe le poulet en lamelles fines.',
      season: 'Melange le yaourt avec sel, poivre, cumin, paprika et citron. Garde une sauce epaisse pour ne pas detremper le wrap.',
      cook: 'Si le poulet est cru, cuis-le a feu moyen 6 a 8 minutes dans une poele antiadhesive. S il est deja cuit, rechauffe-le 1 a 2 minutes.',
      base: 'Chauffe le pain 20 a 30 secondes par face a feu doux pour le rendre souple. Coupe la tomate en petits morceaux.',
      assemble: 'Etale la sauce yaourt, ajoute poulet et tomate, puis roule bien serre. Coupe en deux si tu veux le manger plus facilement.',
      quick: 'utilise du poulet deja cuit et une tortilla prete.',
      fatLoss: 'mets plus de tomate/salade et moins de pain.',
      muscleGain: 'ajoute riz cuit dans le wrap ou prends un pain plus grand.',
    }),
  },
  {
    title: 'Smoothie whey banane',
    category: 'post_training',
    description: 'Shake express pour atteindre les proteines quand la journee file.',
    prepTimeMinutes: 5,
    calories: 330,
    proteinG: 31,
    carbsG: 43,
    fatG: 5,
    difficulty: 'facile',
    tags: ['whey', 'post-training', 'liquide'],
    ingredients: [
      { name: 'whey', quantity: 30, unit: 'g' },
      { name: 'banane', quantity: 1, unit: 'piece' },
      { name: 'lait', quantity: 250, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 30g de whey, 1 banane et 250ml de lait. Prends un shaker ou un blender propre.',
      season: 'Ajoute cannelle ou cacao non sucre si tu veux plus de gout. Evite d ajouter du sucre: la banane suffit souvent.',
      cook: 'Aucune cuisson. Si ton lait est tiede, mets quelques glacons ou laisse le shake 5 minutes au frais.',
      base: 'Verse d abord le lait, puis la whey. Secoue 20 secondes ou mixe 10 secondes pour eviter les grumeaux.',
      assemble: 'Ajoute la banane en morceaux et mixe encore 10 a 15 secondes jusqu a texture lisse.',
      quick: 'sans blender, ecrase la banane a cote et bois whey + lait au shaker.',
      fatLoss: 'utilise eau ou lait demi-ecreme et une demi-banane.',
      muscleGain: 'ajoute avoine ou beurre de cacahuete pour plus de calories.',
    }),
  },
  {
    title: 'Oeufs pain complet',
    category: 'breakfast',
    description: 'Petit-dejeuner simple, solide et economique.',
    prepTimeMinutes: 10,
    calories: 450,
    proteinG: 29,
    carbsG: 44,
    fatG: 18,
    difficulty: 'facile',
    tags: ['budget-etudiant', 'petit-dejeuner', 'proteine'],
    ingredients: [
      { name: 'oeufs', quantity: 3, unit: 'pieces' },
      { name: 'pain', quantity: 90, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 3 oeufs, 90g de pain complet et 1 tomate. Prepare sel, poivre, cumin et un peu de paprika.',
      season: 'Assaisonne les oeufs apres cuisson avec sel, poivre et cumin. Coupe la tomate et ajoute une pincee de sel dessus.',
      cook: 'Pour des oeufs durs, cuis 9 a 10 minutes dans l eau bouillante. Pour des oeufs brouilles, cuis 3 a 4 minutes a feu doux en remuant.',
      base: 'Grille le pain 1 a 2 minutes a la poele ou au grille-pain. Ne le brule pas: feu doux-moyen suffit.',
      assemble: 'Mets les oeufs avec le pain et la tomate. Tu peux ecraser les oeufs sur le pain pour un format tartine.',
      quick: 'fais les oeufs brouilles directement et mange avec pain.',
      fatLoss: 'utilise 2 oeufs et plus de tomate ou concombre.',
      muscleGain: 'garde 3 oeufs et ajoute fromage ou yaourt.',
    }),
  },
  {
    title: 'Pates thon',
    category: 'lunch',
    description: 'Classique etudiant, rapide, pas cher et efficace pour les macros.',
    prepTimeMinutes: 15,
    calories: 610,
    proteinG: 40,
    carbsG: 88,
    fatG: 10,
    difficulty: 'facile',
    tags: ['budget-etudiant', 'thon', 'bulking'],
    ingredients: [
      { name: 'pates', quantity: 250, unit: 'g cuites' },
      { name: 'thon', quantity: 120, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 250g de pates cuites, 120g de thon, 1 tomate, poivre, cumin et herbes si disponibles. Egoutte le thon.',
      season: 'Melange le thon avec poivre, cumin, citron et un peu de sauce tomate si tu en as. Sale legerement seulement si necessaire.',
      cook: 'Si les pates sont crues, cuis-les 8 a 11 minutes dans l eau bouillante salee. Si elles sont deja cuites, rechauffe 2 minutes a feu doux avec une cuillere d eau.',
      base: 'Coupe la tomate en des. Tu peux aussi faire revenir la tomate 2 minutes a feu moyen pour une sauce rapide.',
      assemble: 'Ajoute le thon aux pates chaudes, puis la tomate. Melange 30 secondes sur feu doux pour lier le tout.',
      quick: 'utilise pates deja cuites et thon en boite, pret en 5 minutes.',
      fatLoss: 'baisse les pates a 150g cuites et ajoute plus de legumes.',
      muscleGain: 'augmente les pates ou ajoute un filet d huile d olive.',
    }),
  },
  {
    title: 'Riz oeufs legumes',
    category: 'dinner',
    description: 'Riz saute leger aux oeufs, pratique avec les restes du frigo.',
    prepTimeMinutes: 15,
    calories: 530,
    proteinG: 27,
    carbsG: 72,
    fatG: 16,
    difficulty: 'facile',
    tags: ['rapide', 'budget-etudiant', 'vegetarien'],
    ingredients: [
      { name: 'riz', quantity: 220, unit: 'g cuit' },
      { name: 'oeufs', quantity: 2, unit: 'pieces' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'oignon', quantity: 0.5, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 220g de riz cuit, 2 oeufs, 1 tomate, un demi oignon, sel, poivre, cumin et paprika. Coupe tomate et oignon en petits morceaux.',
      season: 'Bats les oeufs dans un bol avec sel, poivre et cumin. Garde le paprika pour les legumes si tu veux plus de gout.',
      cook: 'Chauffe une poele a feu moyen. Fais revenir oignon et tomate 3 a 4 minutes avec tres peu d huile ou un fond d eau.',
      base: 'Ajoute le riz cuit et rechauffe 2 minutes en remuant. Si le riz colle, ajoute une cuillere d eau.',
      assemble: 'Verse les oeufs battus sur le riz. Remue 2 a 3 minutes a feu moyen-doux jusqu a ce que les oeufs soient cuits.',
      quick: 'utilise riz froid de la veille, il saute mieux et plus vite.',
      fatLoss: 'mets plus de legumes et limite l huile.',
      muscleGain: 'ajoute un oeuf de plus ou augmente le riz.',
    }),
  },
  {
    title: 'Skyr avoine',
    category: 'breakfast',
    description: 'Bol tres proteine pour demarrer haut sans cuisiner.',
    prepTimeMinutes: 5,
    calories: 410,
    proteinG: 36,
    carbsG: 52,
    fatG: 6,
    difficulty: 'facile',
    tags: ['rapide', 'proteine', 'fat_loss'],
    ingredients: [
      { name: 'yaourt', quantity: 250, unit: 'g' },
      { name: 'avoine', quantity: 50, unit: 'g' },
      { name: 'banane', quantity: 0.5, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 250g de skyr ou yaourt grec, 50g d avoine et une demi-banane. Prends un bol assez large pour bien melanger.',
      season: 'Ajoute cannelle, vanille ou cacao non sucre. Si tu veux sucrer, commence par une tres petite quantite de miel.',
      cook: 'Aucune cuisson obligatoire. Pour une texture plus fondante, laisse avoine et yaourt reposer 5 minutes au frais.',
      base: 'Melange le yaourt et l avoine pendant 20 secondes. Si c est trop epais, ajoute une cuillere de lait.',
      assemble: 'Coupe la banane en fines rondelles et ajoute-la au-dessus. Melange seulement au moment de manger.',
      quick: 'mets tout dans un bol et mange directement.',
      fatLoss: 'garde 30 a 40g d avoine et ajoute plus de yaourt 0%.',
      muscleGain: 'ajoute whey, plus d avoine ou une banane entiere.',
    }),
  },
  {
    title: 'Poulet legumes',
    category: 'dinner',
    description: 'Assiette seche et propre pour perte de gras.',
    prepTimeMinutes: 20,
    calories: 430,
    proteinG: 47,
    carbsG: 26,
    fatG: 14,
    difficulty: 'facile',
    tags: ['fat_loss', 'low-carb', 'poulet'],
    ingredients: [
      { name: 'poulet', quantity: 180, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'oignon', quantity: 0.5, unit: 'piece' },
      { name: 'huile d olive', quantity: 5, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 180g de poulet, 1 tomate, un demi oignon, 5ml d huile d olive, sel, poivre, paprika et cumin. Coupe le poulet en filets fins.',
      season: 'Assaisonne le poulet avec sel, poivre, paprika, cumin et citron si disponible. Laisse poser 2 minutes pendant que tu coupes les legumes.',
      cook: 'Chauffe une poele a feu moyen. Cuis le poulet 5 a 7 minutes par face selon l epaisseur, jusqu a cuisson complete.',
      base: 'Dans la meme poele, ajoute tomate et oignon. Fais revenir 3 a 5 minutes a feu moyen-doux pour recuperer les sucs.',
      assemble: 'Sers le poulet avec les legumes chauds. Ajoute persil, salade ou concombre si tu veux plus de volume.',
      quick: 'coupe le poulet en petits morceaux pour cuire en 7 minutes.',
      fatLoss: 'garde peu d huile et double les legumes.',
      muscleGain: 'ajoute riz, pates ou pommes de terre.',
    }),
  },
  {
    title: 'Tortilla oeufs',
    category: 'snack',
    description: 'Snack chaud et dense, parfait quand il reste des oeufs.',
    prepTimeMinutes: 10,
    calories: 420,
    proteinG: 30,
    carbsG: 34,
    fatG: 18,
    difficulty: 'facile',
    tags: ['rapide', 'budget-etudiant', 'oeufs'],
    ingredients: [
      { name: 'oeufs', quantity: 3, unit: 'pieces' },
      { name: 'pain', quantity: 70, unit: 'g' },
      { name: 'fromage', quantity: 20, unit: 'g' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 3 oeufs, 70g de pain et 20g de fromage. Prepare sel, poivre et cumin. Coupe le fromage en petits morceaux.',
      season: 'Bats les oeufs avec sel, poivre et cumin. N ajoute pas trop de sel si ton fromage est deja sale.',
      cook: 'Chauffe une poele a feu doux-moyen. Verse les oeufs et remue 3 a 4 minutes pour obtenir une texture moelleuse.',
      base: 'Ajoute le fromage en fin de cuisson et laisse fondre 30 a 45 secondes. Chauffe le pain a part 1 minute.',
      assemble: 'Ouvre le pain, mets les oeufs au fromage et referme. Presse legerement pour stabiliser le sandwich.',
      quick: 'cuis les oeufs en omelette fine et glisse-la directement dans le pain.',
      fatLoss: 'mets 2 oeufs et reduis le fromage.',
      muscleGain: 'ajoute un oeuf de plus ou prends plus de pain.',
    }),
  },
  {
    title: 'Salade poulet',
    category: 'lunch',
    description: 'Salade sportive, legere, proteinee et facile a ajuster.',
    prepTimeMinutes: 15,
    calories: 460,
    proteinG: 44,
    carbsG: 30,
    fatG: 17,
    difficulty: 'facile',
    tags: ['fat_loss', 'poulet', 'frais'],
    ingredients: [
      { name: 'poulet', quantity: 160, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
      { name: 'oignon', quantity: 0.5, unit: 'piece' },
      { name: 'huile d olive', quantity: 8, unit: 'ml' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 160g de poulet, 1 tomate, un demi oignon, 8ml d huile d olive, citron, sel, poivre et cumin. Coupe la tomate en des et l oignon tres fin.',
      season: 'Assaisonne le poulet avec cumin, paprika, poivre et citron. Si le poulet est deja cuit, assaisonne-le apres l avoir coupe.',
      cook: 'Si le poulet est cru, cuis-le 6 a 8 minutes a feu moyen dans une poele antiadhesive. Laisse tiedir 2 minutes avant de le couper.',
      base: 'Prepare une sauce simple avec citron, huile d olive, sel et poivre. Ajoute un peu de yaourt si tu veux une sauce plus cremeuse.',
      assemble: 'Mets tomate et oignon dans l assiette, ajoute le poulet, puis verse la sauce. Melange juste avant de manger.',
      quick: 'utilise du poulet cuit de la veille et assemble froid.',
      fatLoss: 'mets peu d huile et ajoute concombre ou salade.',
      muscleGain: 'ajoute riz, pain complet ou pois chiches.',
    }),
  },
  {
    title: 'Sandwich oeufs fromage',
    category: 'breakfast',
    description: 'Sandwich chaud de petit-dejeuner, simple et tres rassasiant.',
    prepTimeMinutes: 10,
    calories: 500,
    proteinG: 32,
    carbsG: 46,
    fatG: 22,
    difficulty: 'facile',
    tags: ['budget-etudiant', 'petit-dejeuner', 'rapide'],
    ingredients: [
      { name: 'oeufs', quantity: 2, unit: 'pieces' },
      { name: 'fromage', quantity: 35, unit: 'g' },
      { name: 'pain', quantity: 100, unit: 'g' },
      { name: 'tomate', quantity: 1, unit: 'piece' },
    ],
    instructions: buildInstructions({
      prep: 'Sors 2 oeufs, 35g de fromage, 100g de pain et 1 tomate. Coupe la tomate en tranches et le fromage en lamelles.',
      season: 'Bats les oeufs avec poivre, cumin et un peu de sel. Si tu as du paprika, ajoute une petite pincee.',
      cook: 'Chauffe une poele a feu moyen-doux. Cuis les oeufs en omelette 3 a 5 minutes, puis ajoute le fromage 1 minute pour le faire fondre.',
      base: 'Chauffe le pain 1 minute a feu doux dans une poele seche. Il doit etre souple, pas dur.',
      assemble: 'Mets l omelette au fromage dans le pain, ajoute les tranches de tomate et referme. Coupe en deux si besoin.',
      quick: 'fais des oeufs brouilles au fromage et mets-les directement dans le pain.',
      fatLoss: 'reduis le fromage et ajoute plus de tomate.',
      muscleGain: 'ajoute un oeuf ou accompagne d un yaourt proteine.',
    }),
  },
];

module.exports = { RECIPE_SEEDS };
