ALTER TABLE "foods" ADD COLUMN "nutri_score" VARCHAR(1);
ALTER TABLE "foods" ADD COLUMN "sugars_per_100g" DOUBLE PRECISION;
ALTER TABLE "foods" ADD COLUMN "saturated_fat_per_100g" DOUBLE PRECISION;
ALTER TABLE "foods" ADD COLUMN "fiber_per_100g" DOUBLE PRECISION;
ALTER TABLE "foods" ADD COLUMN "salt_per_100g" DOUBLE PRECISION;
ALTER TABLE "foods" ADD COLUMN "sodium_per_100g" DOUBLE PRECISION;
